# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ldb_case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_number', models.CharField(max_length=100)),
                ('fee_petition_name', models.CharField(max_length=100)),
                ('fee_petition_amt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ldb_client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=10)),
                ('phone_1', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=200)),
                ('ss_num', models.CharField(max_length=11)),
                ('accident_date', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('injury', models.CharField(max_length=2000)),
                ('date_signed_up', models.CharField(max_length=200)),
                ('date_filed', models.CharField(max_length=200)),
                ('statute_of_limit_date', models.CharField(max_length=50)),
                ('referral_source', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ldb_employer',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('employer_name', models.CharField(default='', max_length=100)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=10)),
                ('avg_wkly_wg_ttd_rate', models.IntegerField()),
                ('avg_wkly_wg_ppd_rate', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=14)),
                ('contact_email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ldb_insurance',
            fields=[
                ('ins_co_id', models.AutoField(primary_key=True, serialize=False)),
                ('ins_co_name', models.CharField(max_length=100)),
                ('adj_first_name', models.CharField(max_length=100)),
                ('adj_last_name', models.CharField(max_length=100)),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=10)),
                ('phone_1', models.CharField(max_length=14)),
                ('phone_2', models.CharField(max_length=14)),
                ('fax', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=200)),
                ('claim_number', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ldb_lien',
            fields=[
                ('lien_id', models.AutoField(primary_key=True, serialize=False)),
                ('lien_name', models.CharField(max_length=100)),
                ('lien_amt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ldb_opp_coun',
            fields=[
                ('opp_coun_id', models.AutoField(primary_key=True, serialize=False)),
                ('firm_name', models.CharField(max_length=100)),
                ('att_first_name', models.CharField(max_length=100)),
                ('att_last_name', models.CharField(max_length=100)),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=10)),
                ('phone_1', models.CharField(max_length=14)),
                ('phone_2', models.CharField(max_length=14)),
                ('fax', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ldb_case',
            name='ldb_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyer_app.ldb_client'),
        ),
        migrations.AddField(
            model_name='ldb_case',
            name='ldb_employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyer_app.ldb_employer'),
        ),
        migrations.AddField(
            model_name='ldb_case',
            name='ldb_insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyer_app.ldb_insurance'),
        ),
        migrations.AddField(
            model_name='ldb_case',
            name='ldb_lien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyer_app.ldb_lien'),
        ),
        migrations.AddField(
            model_name='ldb_case',
            name='ldb_opp_coun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyer_app.ldb_opp_coun'),
        ),
    ]
