# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldb_employer',
            name='employer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ldb_insurance',
            name='claim_number',
            field=models.CharField(max_length=200),
        ),
    ]
